# Generated by Django 4.2.10 on 2024-02-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidneypredictor',
            name='albumin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kidneypredictor',
            name='anemia',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kidneypredictor',
            name='bacteria',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kidneypredictor',
            name='blood_glucose_random',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kidneypredictor',
            name='blood_urea',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kidneypredictor',
            name='coronary_artery_disease',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kidneypredictor',
            name='diabetes_mellitus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kidneypredictor',
            name='hpertension',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kidneypredictor',
            name='pedal_edema',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kidneypredictor',
            name='potassium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kidneypredictor',
            name='pus_cell',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kidneypredictor',
            name='pus_cell_clumps',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kidneypredictor',
            name='red_blood_cells',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kidneypredictor',
            name='sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kidneypredictor',
            name='white_blood_cell',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='kidneypredictor',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kidneypredictor',
            name='blood_pressure',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='kidneypredictor',
            name='serum_creatinine',
            field=models.FloatField(default=0),
        ),
    ]
