# Generated by Django 4.2.10 on 2024-02-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_kidneypredictor_albumin_kidneypredictor_anemia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kidneypredictor',
            old_name='hpertension',
            new_name='ypertension',
        ),
    ]
